# ecrire les commandes pour lancer les tests
stages:
  - master
test:
    stage: master
    script:
        - echo "Lancement des tests"
        - tox
        - echo "Fin des tests"
    tags:
        - push
    image: python:3.8