# ecrire les commandes pour lancer les tests
stages:
  - master
  - develop

test:
    stage: master
    script:
        - echo "Lancement des tests"
        - tox
        - echo "Fin des tests"

    tags:
        - docker
    image: python:3.8