name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.8

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox poetry sphinx sphinx-rtd-theme sphinx-autodoc-typehints sphinxcontrib-napoleon

    - name: Build documentation
      run: |
        cd docs
        make html

    - name: Run tests with coverage
      run: |
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage.xml

    - name: Push docs to ReadTheDocs
      run: |
        curl -X POST -d "branches=master" -d "token=${{ secrets.RTD_TOKEN }}" https://readthedocs.org/api/v3/projects/my-arithmetic-dchapart/translations/en/builds/